[package]
name = "sutom_front"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-web = "0.3.1"
dotenv = "0.15.0"
reqwest = "0.11.15"
serde="1.0.159"